// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtoBW7ZbJZMZjHHIqHJyv31-RAO0Tmin4',
    appId: '1:676520421303:web:6bcd99ec5bff01e610aa32',
    messagingSenderId: '676520421303',
    projectId: 'fire-setup-c52bd',
    authDomain: 'fire-setup-c52bd.firebaseapp.com',
    storageBucket: 'fire-setup-c52bd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtjqb_0BJ1eBJ_NWa7lUqcOEhXOiv-jes',
    appId: '1:676520421303:android:93fd8fda54b2537810aa32',
    messagingSenderId: '676520421303',
    projectId: 'fire-setup-c52bd',
    storageBucket: 'fire-setup-c52bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8kP_R4cN0xe7ZkjHRIIxzUBbhMmmUxzk',
    appId: '1:676520421303:ios:c8d8aa67eaa5c66f10aa32',
    messagingSenderId: '676520421303',
    projectId: 'fire-setup-c52bd',
    storageBucket: 'fire-setup-c52bd.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8kP_R4cN0xe7ZkjHRIIxzUBbhMmmUxzk',
    appId: '1:676520421303:ios:c8d8aa67eaa5c66f10aa32',
    messagingSenderId: '676520421303',
    projectId: 'fire-setup-c52bd',
    storageBucket: 'fire-setup-c52bd.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtoBW7ZbJZMZjHHIqHJyv31-RAO0Tmin4',
    appId: '1:676520421303:web:76d3ffdbbb9417f810aa32',
    messagingSenderId: '676520421303',
    projectId: 'fire-setup-c52bd',
    authDomain: 'fire-setup-c52bd.firebaseapp.com',
    storageBucket: 'fire-setup-c52bd.firebasestorage.app',
  );
}
